### ISSUE TITLE
Build failure with GHC-8.6

### ISSUE THREAD

**Issue by phadej** [digital-asset/ghc-lib#282]
```
[ 80 of 264] Compiling GHC.Types.Unique.Supply ( compiler/GHC/Types/Unique/Supply.hs, dist/build/GHC/Types/Unique/Supply.o )

compiler/GHC/Types/Unique/Supply.hs:299:10: error:
    Not in scope: type constructor or class ‘MonadFail’
    Perhaps you meant ‘MonadFix’ (imported from GHC.Utils.Monad)
    |
299 | instance MonadFail UniqSM where
    |          ^^^^^^^^^
cabal: Failed to build ghc-lib-parser-9.0.1.20210207 (which is required by
exe:hlint from hlint-3.3). See the build log above for details.
```

missing lower bounds?

See https://matrix.hackage.haskell.org/#/package/ghc-lib-parser

**Comment by shayne-fletcher** [comment]
Thanks for the heads-up. No, expected failure. To bootstrap ghc-9.0.1 one needs a build compiler >= 8.8.1 (since 2020/03/31, https://gitlab.haskell.org/ghc/ghc/-/commit/57b888c0e90be7189285a6b078c30b26d092380). To bootstrap HEAD one needs >= 8.10.1 (since 2021/03/10, https://gitlab.haskell.org/ghc/ghc/-/commit/0a709dd9876e40c19c934692415c437ac434318c).

Any suggestions on how to stop this being red on the matrix builder? Maybe it's a matter of taking 8.6 out of the "tested at" section of the Cabal files?

**Comment by phadej** [comment]
Use `base` lower bounds as proxy for GHC versions. In fact, it's not even GHC version, because that failure is really `base` library issue, not a some language feature present only in GHC-8.8+ (for which you should use `other-extensions: ...` and double check with `base` lower bound).

**Comment by hamishmack** [comment]
Please use hackage `edit package information` feature to fix the lower bound on the following packages (should be `base >=4.13`):

https://hackage.haskell.org/package/ghc-lib-parser-9.0.1.20210205
https://hackage.haskell.org/package/ghc-lib-parser-9.0.1.20210207

**Comment by shayne-fletcher** [comment]
> Please use hackage `edit package information` feature to fix the lower bound on the following packages (should be `base >=4.13`):
> 
> https://hackage.haskell.org/package/ghc-lib-parser-9.0.1.20210205
> https://hackage.haskell.org/package/ghc-lib-parser-9.0.1.20210207

Done

**Comment by andreasabel** [comment]
Should this issue be closed?  Looks resolved.

**Comment by shayne-fletcher** [comment]
@dylant-da @garyverhaegen-da @akrmn @samuel-williams-da good to close?
